"""Per-beach prose descriptions (PT-BR) for the 'sobre esta praia' section.

~120-180 words each. Friendly carioca/praiano voice. Used by detail.py.
"""

BEACH_DESCRIPTIONS = {
    "copa-p5": (
        "Copacabana Posto 5 fica na ponta de Copacabana mais perto do Forte, "
        "no encontro com o Leme. É a parte mais tranquila da praia: menos badalada "
        "que o Posto 2, com famílias do bairro, pescadores que trazem peixe na areia "
        "e gente que prefere uma água-de-coco sem aperto. A faixa de areia é larga, "
        "o calçadão das ondas pretas e brancas de Burle Marx segue inteiro até o "
        "Leme, e o mar costuma ter ondas curtas, boas pra um banho com cuidado — "
        "tem corrente, principalmente na maré vazante. De manhã pega sol cheio e "
        "o vento entra do sudeste no fim da tarde. Os quiosques entre o Posto 5 e "
        "o Forte servem porção de sardinha e bolinho de bacalhau a preço justo. "
        "Pra chegar, metrô Cardeal Arcoverde e cinco minutos a pé. Estacionamento "
        "na Atlântica é raro nos fins de semana — vá cedo ou de pé."
    ),
    "leblon-mirante": (
        "O Mirante do Leblon fica no final da praia, do lado do Vidigal, onde a "
        "areia encontra a pedra e sobe a rampa pro mirador com vista pros Dois "
        "Irmãos. É o trecho mais cobiçado do Leblon: pôr do sol todo dia com "
        "palmas no fim, surfistas dropando na laje do canto e famílias na faixa "
        "que ainda pega sol. A água tende a ser mais limpa que em Copa — "
        "balneabilidade quase sempre própria — e o mar costuma ser mais formado, "
        "com ondas que entram com força quando o swell é de sul. Tem o quiosque "
        "do Bracarense logo atrás, lendário pelo chope e pelo bolinho de aipim "
        "com camarão. Vento entra do sul à tarde. Vá cedo se quiser sombra de "
        "barraca: o pessoal do bairro chega às 8h da manhã. Ônibus pela Delfim "
        "Moreira ou a pé desde o metrô General Osório."
    ),
    "sao-conrado": (
        "São Conrado é a praia entre os morros — Pedra da Gávea de um lado, Dois "
        "Irmãos do outro — e é também onde aterrissam os parapentes que saltam da "
        "Pedra Bonita. Olhe pra cima num dia de sol e vai ver dezenas de velas "
        "coloridas planando. A praia tem fama de surf consistente: a esquerda da "
        "Pepino é point de longboard e a direita, mais perto do canal, recebe "
        "ondas maiores quando entra swell. Areia grossa, mar fundo logo na "
        "primeira arrebentação — não é praia de criança pequena. Os quiosques "
        "ficam no canto da Pepino e servem moqueca decente. A balneabilidade "
        "oscila, principalmente depois de chuva forte, por causa do canal. Pra "
        "chegar, ônibus pela Niemeyer ou carro com vaga no estacionamento ao "
        "lado do São Conrado Fashion Mall."
    ),
    "cabo-frio-forte": (
        "A Praia do Forte é o cartão-postal de Cabo Frio: areia branquinha e "
        "fininha que range no pé, água verde-clara puxando pra turquesa nos dias "
        "de céu aberto e o Forte São Mateus de pedra do século XVII no canto, "
        "vigiando a entrada do canal do Itajuru. É uma das praias mais "
        "fotografadas da Região dos Lagos, com mar geralmente calmo, bom pra "
        "criança e pra quem quer nadar sem susto. A água é fria pro padrão "
        "carioca — ressurgência sopra água gelada nessa costa — então não "
        "estranhe os 18 graus em pleno janeiro. A faixa de areia é enorme na "
        "maré baixa e tem ambulantes de queijo coalho e biscoito de polvilho o "
        "dia todo. Quiosques no calçadão da Avenida do Contorno. Estacionamento "
        "fácil em dia de semana, complicado no feriado."
    ),
    "balneario-camboriu": (
        "A Praia Central de Balneário Camboriú é a mais famosa de Santa Catarina "
        "e a mais polêmica: prédios altíssimos formam um paredão de sombra que, "
        "depois do meio da tarde, cobre boa parte da areia. Mesmo assim, é um "
        "fenômeno — calçadão largo, ciclovia, palmeiras, e a faixa de areia foi "
        "alargada num projeto recente de engorda. Mar verde, ondas pequenas a "
        "médias, bom pra banho e pra criança. O bondinho aéreo que sai do "
        "Barra Sul cruza pra Praia de Laranjeiras, vale o passeio. À noite a "
        "orla vira a mais badalada do sul, com bares, sorveterias e o pessoal "
        "andando de bike. Vá de manhã se quiser sol o dia todo: depois das 15h "
        "a sombra dos prédios chega na água. Estacionamento rotativo na Atlântica."
    ),
    "balneario-rincao": (
        "Balneário Rincão é cidade nova, emancipada de Içara em 2013, no extremo "
        "sul catarinense quase na fronteira com o Rio Grande. A praia é uma "
        "faixa enorme de areia clara que se estende por quilômetros sem prédio "
        "grudado na água — diferente da Camboriú, aqui dá pra andar de carro "
        "na areia em alguns trechos e a vibe é mais família-do-interior, com "
        "casas de veraneio gaúchas. O mar é aberto, com ondas formadas e "
        "correntes — atenção pra criança. Vento sul costuma soprar forte à "
        "tarde, e é justamente isso que atrai o pessoal do kite e do windsurf. "
        "Tem o Farol do Rincão como ponto de referência. Temporada de verão é "
        "agitada com gauchada; fora da temporada, é praticamente deserta. Leve "
        "guarda-sol — sombra natural é zero."
    ),
    "floripa-barra-lagoa": (
        "Barra da Lagoa fica no Leste de Florianópolis, onde a Lagoa da "
        "Conceição encontra o mar pelo canal. É o melhor dos dois mundos: de um "
        "lado, mar aberto com ondas constantes que fizeram a fama do surf "
        "catarinense; do outro, o canal de água parada onde a molecada pula da "
        "ponte e o pessoal rema de SUP. Vila de pescadores com casas coloridas, "
        "restaurantes de frutos do mar fresquinhos e a famosa passarela suspensa "
        "que liga as duas margens. O molhe de pedras no canto direito separa a "
        "Barra da Praia da Galheta (naturismo). Mar pode estar bravo — sempre "
        "tem bandeira e guarda-vidas no verão. Vá no Caminho dos Açores pra um "
        "almoço de tainha. Ônibus direto do TICEN e estacionamento pago perto "
        "do canal. Água verde-azulada quando o vento é norte."
    ),
    "morro-terceira": (
        "A Terceira Praia de Morro de São Paulo é a queridinha de quem quer "
        "Bahia sem o agito da Segunda. Fica logo depois da Segunda, separada por "
        "uma faixinha de pedras, e tem o mar mais calmo do arquipélago: na maré "
        "baixa formam-se piscinas naturais de água morna e cristalina onde dá "
        "pra ficar boiando vendo peixinho. Pousadas pé-na-areia, restaurantes "
        "de moqueca de polvo, e o som ambiente é violão acústico, não paredão. "
        "Areia clara, coqueiros, e do lado direito sai a trilha pras praias "
        "mais desertas (Quarta, Quinta, Encanto). Não tem carro na ilha — "
        "tudo a pé ou tratorzinho desde o cais. Vá na maré baixa do meio-dia "
        "pra pegar as piscinas; consulte a tábua. Catamarã sai de Salvador "
        "(Terminal Marítimo) ou Valença."
    ),
    "santos-gonzaga": (
        "A Praia do Gonzaga é o coração turístico de Santos, com o calçadão de "
        "jardins mais longo do mundo segundo o Guinness — sete quilômetros de "
        "canteiros desenhados, palmeiras imperiais e ciclovia que vai da Ponta "
        "da Praia até o José Menino. A faixa de areia é larga, o mar é manso "
        "(o porto e a Ilha de Santo Amaro quebram a ondulação) e a água tem "
        "aquela coloração marrom-clara típica do estuário — não é caribe, mas "
        "a balneabilidade melhorou bastante nos últimos anos. Bom pra família, "
        "pra caminhar, pra andar de bike. Aquário Municipal e Museu do Café "
        "perto. Quiosques no canal 3 servem porção de peixe frito clássica. "
        "Vento entra do sul à tarde. Pra chegar, VLT desde o Centro Histórico "
        "ou ônibus pela Avenida Ana Costa. Estacionamento pago na Bartolomeu."
    ),
    "guaruja-enseada": (
        "A Praia da Enseada é a maior do Guarujá — cinco quilômetros e meio de "
        "areia que vão do Tortugas até o Pernambuco. Mar geralmente calmo, com "
        "ondas pequenas que servem pra iniciante de surf e pra criança, e "
        "infraestrutura completa: hotéis pé-na-areia, quiosques a cada cem "
        "metros, banana-boat, jet-ski, ambulante de milho cozido e camarão na "
        "vara. É a praia clássica do paulistano de classe média que sobe a "
        "serra no fim de semana. A água oscila — fica mais limpa na ponta do "
        "Pernambuco, mais carregada perto da Pitangueiras. Acquário do Guarujá "
        "fica em frente. Vá cedo no feriado: a Cônego Domênico Rangoni "
        "engarrafa feio depois das 9h. Estacionamento em rua paga ou nos "
        "shoppings da orla. Vento sudeste à tarde mexe com a areia."
    ),
    "praia-grande-boqueirao": (
        "O Boqueirão fica no meio de Praia Grande, entre o Canto do Forte e o "
        "Aviação, e é o trecho mais movimentado da cidade — calçadão amplo, "
        "ciclovia, quiosques colados um no outro e a roda-gigante (a Praia "
        "Grande Eye) como ponto de referência. Mar de Praia Grande é o típico "
        "litoral central paulista: ondulação média, água meio escura por causa "
        "da pluma do Porto de Santos vizinho, balneabilidade que oscila. Bom "
        "pra banho com cuidado, ótimo pra caminhar à beira d'água — a praia é "
        "rasa e a maré baixa expõe uma faixa enorme. Camelô vende porção de "
        "siri-mole e espetinho. É a praia mais barata e democrática da Baixada, "
        "muito procurada por excursões de ônibus. Estacionamento na Avenida "
        "Costa e Silva (a rotativa) ou nos prédios alugando vaga."
    ),
    "natal-ponta-negra": (
        "Ponta Negra é A praia de Natal — meio-lua de areia clara com o Morro "
        "do Careca no canto sul, aquele duna gigante coberta de vegetação na "
        "base que aparece em todo cartão-postal do RN (e que não pode mais ser "
        "escalada, pra preservar). Água morna o ano inteiro, cor verde-esmeralda "
        "puxando pro azul, ondas pequenas a médias que servem pra surf "
        "iniciante. A orla é um dos lugares mais animados do Nordeste: bares "
        "abertos até tarde, forró ao vivo, casas de show, ambulante de "
        "tapioca recheada. Vento alísio sopra constante do leste — ótimo pra "
        "kite mais pro norte (Genipabu), aqui ajuda a refrescar. Comida típica: "
        "peixe na telha, carne de sol com macaxeira. Aeroporto fica a vinte "
        "minutos. Vá num bugue passear pelas dunas vizinhas — programa "
        "obrigatório de Natal."
    ),
}
